config/routes.rb
require 'sidekiq/api'
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'appointment_summaries#new'

  mount GovukAdminTemplate::Engine, at: '/style-guide'
  mount Sidekiq::Web => '/sidekiq', constraints: AuthenticatedUser.new

  namespace :api, constraints: { format: :json } do
    namespace :v1 do
      resources :searches, only: :index
      resources :appointment_summaries, only: %i(show update)
    end
  end

  resources :appointment_summaries, only: %i(index new create update show) do
    collection do
      get :creating
      get :done
      post :confirm
    end
  end

  scope path: 'styleguide', controller: 'styleguide' do
    scope path: 'pages' do
      get 'input', action: 'pages_input'
      get 'output-elements', action: 'pages_output_elements'
    end
  end

  namespace :admin do
    resources :appointment_summaries, only: [:index, :edit, :update]
  end
end

app/models/appointment_summary.rb
class AppointmentSummary < ApplicationRecord # rubocop:disable Metrics/ClassLength
  enum :notify_status, %i(pending delivered failed ignoring)

  DIGITAL_BY_DEFAULT_START_DATE = Date.new(2016, 6, 21)
  # bassed off: https://github.com/alphagov/notifications-utils/blob/master/notifications_utils/recipients.py#L22
  EMAIL_REGEXP = Regexp.union(
    /\A([^";@\s\.]+\.)*[^";@\s\.]+@([^";@\s\.]+\.)+[a-zA-Z]{2,10}\z/,
    /\A\z/
  )

  scope :excluding_digital_by_default, lambda {
    where(
      %(
        appointment_summaries.requested_digital IS FALSE
        OR appointment_summaries.date_of_appointment < ?
      ),
      DIGITAL_BY_DEFAULT_START_DATE
    )
  }

  scope :needing_notify_delivery_check, lambda {
    where(
      requested_digital: true,
      notify_completed_at: nil,
      created_at: 2.days.ago.beginning_of_day..Time.zone.now
    ).where.not(notification_id: '')
  }

  def postcode=(str)
    if str.blank?
      super
    else
      super UKPostcode.parse(str).to_s
    end
  end

  TITLES = %w(Mr Mrs Miss Ms Mx Dr Reverend Sir Dame).freeze

  belongs_to :user

  validates :title, inclusion: { in: TITLES }, allow_blank: true
  validates :last_name, presence: true
  validates :date_of_appointment, timeliness: { on_or_before: -> { Time.zone.today },
                                                on_or_after: Date.new(2015),
                                                type: :date }
  validates :reference_number, presence: true

  with_options numericality: true, allow_blank: true, if: :eligible_for_guidance? do |eligible|
    eligible.validates :value_of_pension_pots
    eligible.validates :upper_value_of_pension_pots
  end

  validates :guider_name, presence: true, if: :pension_wise?

  validates :address_line_1, presence: true, length: { maximum: 50 }, if: :requested_postal?
  validates :address_line_2, length: { maximum: 50 }, if: :requested_postal?
  validates :address_line_3, length: { maximum: 50 }, if: :requested_postal?
  validates :town, presence: true, length: { maximum: 50 }, if: :requested_postal?
  validates :county, length: { maximum: 50 }, if: :requested_postal?
  validates :postcode, presence: true
  validates :postcode, postcode: true, if: :postcode_format_required?
  validates :country, presence: true, inclusion: { in: Countries.all }, if: :requested_postal?

  validates :has_defined_contribution_pension,
            presence: true,
            inclusion: {
              in: %w(yes no unknown),
              allow_blank: true,
              message: '%{value} is not a valid value'
            },
            if: :pension_wise?

  validates :has_defined_benefit_pension,
            inclusion: {
              in: %w(yes no),
              message: '%{value} is not a valid value'
            },
            if: -> { has_defined_contribution_pension == 'no' }

  validates :considering_transferring_to_dc_pot,
            inclusion: {
              in: %w(yes no),
              message: '%{value} is not a valid value'
            },
            if: -> { has_defined_benefit_pension == 'yes' }

  validates :format_preference, inclusion: { in: %w(standard large_text braille) }
  validates :appointment_type, inclusion: { in: %w(standard 50_54) }
  validates :covering_letter_type,
            inclusion: { in: %w(section_32 adjustable_income inherited_pot fixed_term_annuity) },
            allow_blank: true
  validates :number_of_previous_appointments, inclusion: { in: 0..3 }
  validates :email, format: EMAIL_REGEXP
  validates :email, presence: true, if: :requested_digital?
  validates :telephone_appointment, inclusion: { in: [true, false] }

  with_options presence: true, if: :requires_next_steps? do
    validates :updated_beneficiaries
    validates :regulated_financial_advice
    validates :kept_track_of_all_pensions
    validates :interested_in_pension_transfer
    validates :created_retirement_budget
    validates :know_how_much_state_pension
    validates :received_state_benefits
    validates :pension_to_pay_off_debts
    validates :living_or_planning_overseas
    validates :finalised_a_will
    validates :setup_power_of_attorney
  end

  def self.for_redaction
    where
      .not(first_name: Redactor::REDACTED)
      .where('created_at < ?', 2.years.ago.beginning_of_day)
  end

  def self.editable_column_names
    column_names - %w(id created_at updated_at user_id notification_id)
  end

  def self.for_tap_reissue(tap_reference)
    where(
      reference_number: tap_reference,
      requested_digital: true,
      telephone_appointment: true
    ).order(created_at: :desc).first
  end

  def standard?
    appointment_type == 'standard'
  end

  def requested_postal?
    !requested_digital?
  end

  def has_defined_contribution_pension # rubocop:disable Naming/PredicateName
    return 'unknown' if due_diligence?

    super
  end

  def format_preference
    super || 'standard'
  end

  def appointment_type
    super || 'standard'
  end

  def eligible_for_guidance?
    %w(yes unknown).include?(has_defined_contribution_pension) ||
      (has_defined_benefit_pension == 'yes' && considering_transferring_to_dc_pot == 'yes')
  end

  def can_be_emailed?
    requested_digital? && email.present?
  end

  def stop_checking!
    update(
      notify_completed_at: Time.zone.now,
      notify_status: :ignoring
    )
  end

  def full_name
    "#{title} #{first_name} #{last_name}"
  end

  def postal_address
    [
      address_line_1,
      address_line_2,
      address_line_3,
      town,
      county,
      postcode
    ].reject(&:empty?).join("\n")
  end

  def organisation_id
    user&.organisation_content_id
  end

  def supplementary_info_selected?
    supplementary_benefits ||
      supplementary_debt ||
      supplementary_ill_health ||
      supplementary_defined_benefit_pensions ||
      supplementary_pension_transfers
  end

  def braille_notification?
    eligible_for_guidance? && braille? && !requested_digital?
  end

  def braille?
    format_preference == 'braille'
  end

  def pension_wise?
    schedule_type == 'pension_wise'
  end

  def due_diligence?
    schedule_type == 'due_diligence'
  end

  def notify_via_email
    return unless can_be_emailed?

    if due_diligence?
      NotifyDueDiligenceViaEmail.perform_later(self)
    else
      NotifyViaEmail.perform_later(self)
    end
  end

  def requires_next_steps?
    eligible_for_guidance? && pension_wise?
  end

  private

  def postcode_format_required?
    requested_postal? && Countries.uk?(country)
  end
end

app/controllers/admin/appointment_summaries_controller.rb
# frozen_string_literal: true
module Admin
  class AppointmentSummariesController < ::ApplicationController
    before_action :authenticate_as_analyst!

    def index
      @appointment_form = AppointmentSummaryBrowser.new(form_params)

      respond_to do |format|
        format.html
        format.csv { render csv: AppointmentSummaryCsv.new(@appointment_form.results) }
      end
    end

    def edit
      @appointment_summary = AppointmentSummary.find(params[:id])
    end

    def update
      @appointment_summary = AppointmentSummary.find(params[:id])

      if @appointment_summary.update(appointment_summary_params)
        NotifyViaEmail.perform_later(@appointment_summary) if @appointment_summary.can_be_emailed?
        redirect_to admin_appointment_summaries_path
      else
        render :edit
      end
    end

    private

    def form_params
      params
        .fetch(:appointment_summary_browser, {})
        .permit(:start_date, :end_date, :search_string, :requested_digital, :telephone_appointment)
        .merge(page: params[:page])
    end

    def appointment_summary_params
      params.require(:appointment_summary)
            .permit(:email)
            .merge(notification_id: nil)
    end
  end
end

app/controllers/api/v1/appointment_summaries_controller.rb
module Api
  module V1
    class AppointmentSummariesController < ActionController::Base
      include GDS::SSO::ControllerMethods

      before_action { authorise_user!(User::API_USER_PERMISSION) }

      def show
        @appointment_summary = AppointmentSummary.for_tap_reissue(params[:id])

        if @appointment_summary
          render json: @appointment_summary.to_json(only: [:email])
        else
          head :not_found
        end
      end

      def update
        @appointment_summary = AppointmentSummary.for_tap_reissue(params[:id])

        if @appointment_summary.update(email: params[:email])
          @appointment_summary.notify_via_email
          CreateTapActivity.perform_later(@appointment_summary, params[:initiator_uid])

          head :ok
        else
          head :unprocessable_entity
        end
      end
    end
  end
end

app/controllers/appointment_summaries_controller.rb
# frozen_string_literal: true
class AppointmentSummariesController < ApplicationController
  before_action :authenticate_as_team_leader!, only: :index
  before_action :check_can_create_appointments!, only: [:new, :confirm, :create]
  before_action :load_summary, only: %i(new email_confirmation update confirm)

  def index
    @appointment_form = AppointmentSummaryFinder.new(
      search_string: params.dig(:appointment_summary_finder, :search_string),
      search_date: params.dig(:appointment_summary_finder, :search_date)
    )
  end

  def new
    if instruct?
      render :summarise_via_tap
    elsif tap_user_needs_phone_permission?
      render :tap_user_needs_phone_permission
    else
      @appointment_summary.assign_attributes(appointment_summary_params)
    end
  end

  def confirm
    @appointment_summary.assign_attributes(appointment_summary_params)

    if @appointment_summary.valid?
      @output_document = OutputDocument.new(@appointment_summary)
    else
      render :new
    end
  end

  def create
    @appointment_summary = AppointmentSummary.create!(appointment_summary_params)
    send_notifications(@appointment_summary)

    respond_to do |format|
      format.html { redirect_to done_appointment_summaries_path }
      format.json { render json: ajax_response_paths(@appointment_summary) }
    end
  end

  def update
    @appointment_summary.update!(appointment_summary_params)
    send_notifications(@appointment_summary)

    respond_to do |format|
      format.html { redirect_to done_appointment_summaries_path }
      format.json { render json: ajax_response_paths(@appointment_summary) }
    end
  end

  def show
    appointment_summary = AppointmentSummary.find(params[:id])
    output_document = OutputDocument.new(appointment_summary)

    send_data output_document.pdf,
              filename: 'pension_wise.pdf', type: 'application/pdf',
              disposition: :inline
  end

  def done
  end

  def creating
  end

  private

  def tap_user_needs_phone_permission?
    params.dig(:appointment_summary, :telephone_appointment) == 'true' &&
      !current_user.has_permission?(User::TELEPHONE_APPOINTMENT_PERMISSION) &&
      !current_user.team_leader?
  end

  def instruct?
    !current_user.has_permission?(User::FACE_TO_FACE_PERMISSION) && !params[:appointment_summary]
  end

  def check_can_create_appointments!
    authorise_user!(
      any_of: [
        User::TELEPHONE_APPOINTMENT_PERMISSION,
        User::FACE_TO_FACE_PERMISSION
      ]
    )
  end

  def load_summary
    @appointment_summary = AppointmentSummary.find_or_initialize_by(
      reference_number: params.dig(:appointment_summary, :reference_number),
      telephone_appointment: telephone_appointment?
    )
  end

  def send_notifications(appointment_summary)
    appointment_summary.notify_via_email

    CreateTapActivity.perform_later(appointment_summary, current_user) if telephone_appointment?
    BrailleNotification.perform_later(appointment_summary) if appointment_summary.braille_notification?
  end

  def telephone_appointment?
    params.dig(:appointment_summary, :telephone_appointment) == 'true' &&
      current_user.has_permission?(User::TELEPHONE_APPOINTMENT_PERMISSION)
  end
  helper_method :telephone_appointment?

  def appointment_summary_params
    params
      .fetch(:appointment_summary, {})
      .permit(AppointmentSummary.editable_column_names)
      .merge(user: current_user, telephone_appointment: telephone_appointment?)
      .reverse_merge(date_of_appointment: Date.current)
  end

  def ajax_response_paths(appointment_summary)
    {
      done_path: done_appointment_summaries_path,
      pdf_path: appointment_summary_path(appointment_summary, format: 'pdf')
    }
  end
end

app/views/appointment_summaries/_confirmation_button.html.erb
<%
  options = {}

  if local_assigns[:url]
    options[:url]    = local_assigns[:url]
    options[:method] = local_assigns.fetch(:method) { :post }
  end
%>
<%= form_for local_assigns.fetch(:appointment_summary), options do |f| %>

  <% AppointmentSummary.editable_column_names.each do |field| %>
    <%= f.hidden_field field %>
  <% end %>

  <%= f.submit local_assigns.fetch(:submit_button_text),
    class: (%w(btn) | Array(local_assigns[:submit_button_classes])),
    data: { disable_with: 'Please wait...' } %>
<% end %>

app/views/appointment_summaries/_preview_form.html.erb
<%
  options = {}

  if local_assigns[:url]
    options[:url]    = local_assigns[:url]
    options[:method] = local_assigns.fetch(:method) { :post }
  end
%>
<%= form_for local_assigns.fetch(:appointment_summary), options do |f| %>

  <% AppointmentSummary.editable_column_names.each do |field| %>
    <%= f.hidden_field field %>
  <% end %>

  <%= f.submit local_assigns.fetch(:submit_button_text),
    class: (%w(btn) | Array(local_assigns[:submit_button_classes])),
    data: { disable_with: 'Please wait...' } %>
<% end %>

app/views/appointment_summaries/confirm.html.erb
<div class="page-header">
  <h1><%= title 'Confirm details' %><% if @appointment_summary.due_diligence? %> <small class="t-due-diligence-banner">Due Diligence</small><% end %></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <p class="alert alert-warning">
      Check the customer details below and edit or confirm.
    </p>

    <table class="table lead">
      <tbody>
        <tr>
          <td class="active" width="35%"><b>Customer name</b></td>
          <td><%= @appointment_summary.full_name %></td>
        </tr>
        <% if @appointment_summary.requested_digital %>
          <tr>
            <td class="active" width="35%"><b>Email</b></td>
            <td><%= @appointment_summary.email %></td>
          </tr>
        <% end %>
        <% unless @appointment_summary.requested_digital %>
          <tr>
            <td class="active" width="35%"><b>Address</b></td>
            <td>
              <address><%= @appointment_summary.postal_address %></address>
            </td>
          </tr>
        <% end %>
        <tr>
          <td class="active" width="35%"><b>Date of appointment</b></td>
          <td><%= @appointment_summary.date_of_appointment.to_fs(:govuk_date) %></td>
        </tr>
        <% if @appointment_summary.due_diligence? %>
        <tr>
          <td class="active t-unique-reference-number" width="35%"><b>Unique reference number</b></td>
          <td><%= @appointment_summary.unique_reference_number %></td>
        </tr>
        <% end %>
        <% if @appointment_summary.pension_wise? %>
          <tr>
            <td class="active t-guider-name" width="35%"><b>Guider Name</b></td>
            <td><%= @appointment_summary.guider_name %></td>
          </tr>
          <% if @appointment_summary.eligible_for_guidance? %>
            <tr class="t-supplementary-info">
              <td class="active" width="35%"><b>Supplementary info</b></td>
              <td>
                <% if @appointment_summary.supplementary_info_selected? %>
                  <ul>
                    <%= content_tag(:li, 'Transferring a Final Salary or Career Average Pension') if @appointment_summary.supplementary_defined_benefit_pensions %>
                  </ul>
                <% else %>
                  None selected
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <div class="confirm-submit-buttons">
      <%=
        submit_button_classes = %w(btn-primary t-confirm)
        submit_button_classes << 'js-save-and-open' unless @appointment_summary.requested_digital?

        render 'confirmation_button', appointment_summary: @appointment_summary,
               submit_button_text: 'Confirm summary document', submit_button_classes: submit_button_classes
      %>

      <%= render 'confirmation_button', url: new_appointment_summary_path, method: :get, appointment_summary: @appointment_summary,
               submit_button_text: 'Edit summary document', submit_button_classes: %w(btn-danger t-back) %>
    </div>
  </div>
</div>

<script>
<%
  path = if @appointment_summary.persisted?
           appointment_summary_path(@appointment_summary, format: :json)
         else
           appointment_summaries_path(format: :json)
         end
%>
$('.js-save-and-open').click(function(e){
  var popupWindow = window.open('<%= creating_appointment_summaries_path %>');

  $.post('<%= path %>', $(this.form).serialize())
    .done(function(data) {
      popupWindow.location = data.pdf_path;
      window.location = data.done_path;
    })
    .fail(function() {
      popupWindow.close();
      alert('Error saving the summary document. Please try again.');
    });

  e.preventDefault();
});
</script>

app/views/appointment_summaries/create.html.erb
<h2>Done!</h2>

<p>Appointment details have been saved. A Pension Wise Summary Document will be printed and dispatched to the
  customer shortly.</p>

<p style='padding-top: 1em'><%= link_to 'Generate another', root_path, class: %w(btn-success btn-lg) %></p>

app/views/appointment_summaries/creating.html.erb
<div class="page-header">
  <h1><%= title 'Creating PDF' %></h1>
</div>


<p>The summary of the options will open in this window.</p>

app/views/appointment_summaries/done.html.erb
<div class="page-header">
  <h1><%= title 'Appointment summary created' %></h1>
</div>

<p>An appointment summary has been created. Digital versions will be sent automatically.</p>

<p>If the customer requested a postal version, download and print the summary to send to them.</p>

app/views/appointment_summaries/index.html.erb
<div class="page-header">
  <h1><%= title 'Reprint Summary' %></h1>
</div>

<div class="col-md-6">
  <div class="row">
    <div class="well col-md-11">
      <%= form_for @appointment_form, url: appointment_summaries_path, method: :get, html: { class: 'inline form-inline' } do |f| %>
        <div class="form-group">
          <%= f.label :search_date, 'Appointment Date', class: 'inline' %>
          <%= f.text_field :search_date, class: 'form-control t-date-search', placeholder: 'DD/MM/YYYY' %>
        </div>
        <%= f.submit 'Search', class: 'btn btn-default t-date-search-button' %>
      <% end %>
    </div>
  </div>
</div>
<div class="col-md-6">
  <div class="row">
    <div class="well col-md-11 col-md-offset-1">
      <%= form_for @appointment_form, url: appointment_summaries_path, method: :get, html: { class: 'inline form-inline' } do |f| %>
        <div class="form-group">
          <%= f.label :search_string, 'Reference Number', class: 'inline' %>
          <%= f.text_field :search_string, class: 'form-control t-search', placeholder: 'Reference Number' %>
        </div>
        <%= f.submit 'Search', class: 'btn btn-default t-search-button' %>
      <% end %>
    </div>
  </div>
</div>

<table class="table table-striped table-bordered">
  <thead>
    <tr class="table-header">
      <th scope="col">Booking<br>reference</th>
      <th scope="col">Guider</th>
      <th scope="col">Customer</th>
      <th scope="col">Appointment<br>date</th>
      <th scope="col">Created<br>at</th>
      <th scope="col">Email copy<br>requested</th>
      <th scope="col">Email</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @appointment_form.results.each do |summary| %>
      <tr class="t-appointment">
        <td class="t-reference-number"><%= summary.reference_number %></td>
        <td><%= summary.guider_name %> (<%= summary.telephone_appointment? ? 'phone' : 'F2F' %>)</td>
        <td><%= "#{summary.title} #{summary.first_name} #{summary.last_name}" %></td>
        <td><%= summary.date_of_appointment.to_fs(:gov_uk) %></td>
        <td><%= summary.created_at.to_fs(:govuk_date) %></td>
        <td><%= summary.requested_digital ? 'Yes' : 'No' %></td>
        <td><%= summary.email %></td>
        <td>
          <% unless summary.requested_digital? %>
            <%= link_to 'Reprint', new_appointment_summary_path(appointment_summary: summary.attributes), class: 't-reprint' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/appointment_summaries/summarise_via_tap.html.erb
<div class="page-header">
  <h1>Create appointment summary in planner</h1>
</div>

<p class="help-block t-use-tap">After the appointment status is updated use the Telephone
Appointment Planner to create the summary.</p>

app/views/appointment_summaries/tap_user_needs_phone_permission.html.erb
<div class="page-header">
  <h1>You do not have the required permission</h1>
</div>

<p class="help-block t-no-permission">You need the telephone guider permission to summarise appointments via TAP.</p>