config/routes.rb
require 'sidekiq/api'
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'appointment_summaries#new'

  mount GovukAdminTemplate::Engine, at: '/style-guide'
  mount Sidekiq::Web => '/sidekiq', constraints: AuthenticatedUser.new

  namespace :api, constraints: { format: :json } do
    namespace :v1 do
      resources :searches, only: :index
      resources :appointment_summaries, only: %i(show update)
    end
  end

  resources :appointment_summaries, only: %i(index new create update show) do
    collection do
      get :creating
      get :done
      post :confirm
    end
  end

  scope path: 'styleguide', controller: 'styleguide' do
    scope path: 'pages' do
      get 'input', action: 'pages_input'
      get 'output-elements', action: 'pages_output_elements'
    end
  end

  namespace :admin do
    resources :appointment_summaries, only: [:index, :edit, :update]
  end
end

app/views/layouts/application.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
<% end %>

<% content_for :app_title, 'Summary Document Generator' %>
<% content_for :page_title, title %>

<% if user_signed_in? %>
  <%= content_for :navbar_right do %>
    <div class='session-details-panel'>
      <%= link_to current_user.name, Plek.current.find('signon') %>
      &bull; <%= link_to 'Sign out', gds_sign_out_path %>
    </div>
  <% end %>

  <% if current_user.team_leader? || current_user.analyst? %>
    <% content_for :navbar_items do %>
      <% if current_user.team_leader? %>
        <li>
          <%= link_to 'Reprint', appointment_summaries_path %>
        </li>
      <% end %>
      <% if current_user.analyst? %>
        <li>
          <%= link_to 'Reporting', admin_appointment_summaries_path %>
        </li>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<% content_for(:content) do %>
  <%= render 'shared/alerts' %>
  <%= yield %>
<% end %>

<%= render template: 'layouts/govuk_admin_template' %>

app/views/layouts/error.html.erb
<%= render template: 'layouts/application' %>